name: buildauto

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with: 
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Grant execute permissions for eslint
      run: chmod +x ./node_modules/.bin/eslint

    - name: Run lint
      run: npm run lint
